name: Node.js CI

on:
  push:
    branches:
      - nodejs_server
  pull_request:
    branches:
      - nodejs_server

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build project (if applicable)
        run: node index.js   # Your build command if needed

      - name: Run tests and mutation testing
        run: |
          # Command to run unit tests
          npm run test:unit

          # Command to run mutation testing
          npm run test:mutation

